# Form implementation generated from reading ui file '.\ui\change_password.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(341, 135)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 321, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lbl_oldpass = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_oldpass.setObjectName("lbl_oldpass")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lbl_oldpass)
        self.le_oldpass = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.le_oldpass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.le_oldpass.setObjectName("le_oldpass")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.le_oldpass)
        self.lbl_newpass = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_newpass.setObjectName("lbl_newpass")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lbl_newpass)
        self.le_newpass = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.le_newpass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.le_newpass.setObjectName("le_newpass")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.le_newpass)
        self.lbl_confirmpass = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_confirmpass.setObjectName("lbl_confirmpass")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lbl_confirmpass)
        self.le_confirmpass = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.le_confirmpass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.le_confirmpass.setObjectName("le_confirmpass")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.le_confirmpass)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_oldpass.setText(_translate("Dialog", "Old Password"))
        self.lbl_newpass.setText(_translate("Dialog", "New Password"))
        self.lbl_confirmpass.setText(_translate("Dialog", "Confirm Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
